class Day{
public static void mian(String[]args)
{
switch(3)
{
case 1:
System.out.println("sunday");
break;
case 2:
System.out.println("Monday");
break;
case 3:
System.out.println("Tuesday");
break;
case 4:
System.out.println("wednesday");
break;
case 5:
System.out.println("Thursday");
break;
case 6:
System.out.println("Friday");
break;
case 7:
System.out.println("saturday");
break;
default:
System.out.println("Enter vaild Number");
}
}
}
